basePath: /
host: temp.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Small demo appliction serving albums
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Kopwerk Demo
  version: "1.0"
paths:
  /album/{id}:
    get:
      description: get a album by its id
      operationId: get album by id
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
  /albums:
    get:
      description: get all albums
      operationId: get albums
      parameters:
      - description: Album name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses: {}
  /health:
    get:
      description: get healthcheck
      operationId: health
      produces:
      - application/json
      responses: {}
      summary: Check the health of the server
swagger: "2.0"
